### PR TITLE
fixing a fatal error by throwing an exception

### LINKED ISSUE #69: Fatal error when trying to get messages without running validation
I get a fatal error when running the following code:

```php
$validator = new Particle\Validator\Validator();

echo $validator->getMessages();
```

While the above code logically incorrect (no validation has been run), it could happen and should at least not fatal.

### PR DESCRIPTION
**Pull request by skoop**
This should fix #69

### CODE REVIEW

File: src/Validator.php [hunk 1]
```diff
@@ -130,10 +131,16 @@ public function getValues()
     /**
      * Returns an array of all validation failures.
      *
+     * @throws ValidationNotRunException
      * @return array
      */
     public function getMessages()
     {
+        if (is_null($this->messageStack))
+        {
```
Comment (RickvdStaaij) [inline src/Validator.php]: Not PSR-2 valid :scream:

Comment (skoop) [inline src/Validator.php]: oops, fixed!

**Comment by RickvdStaaij** [comment]
This is OK with me to add to version 1 :) :+1:
